import LessonCode from './LessonCode';
import {tiers,TierBadge,TierNote} from './tiers';
import {useEffect,useRef,useState,type CSSProperties,type ReactNode} from 'react';
import {BookOpen,GitBranch,Search,Download,Upload,Undo2,Check,Lock,ArrowRight,ArrowLeftRight,X,Leaf,LayoutGrid,List,Settings2,ExternalLink,Bookmark,Info,ChevronRight} from 'lucide-react';
import {branches,skills,byId,soulColors,initialState,slotKey,slotLabel,sameSlot,soulFor,status,previewMove,moveSkill,commitProblems,commitSkill,validateState,type State,type Slot} from './model';
import {loadState,saveState} from './storage';
import Encyclopedia from './Encyclopedia';

function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const d=ref.current!;d.showModal();return()=>d.close();},[]);
 return <dialog ref={ref} className={wide?'modal wide':'modal'} onCancel={e=>{e.preventDefault();onClose();}} onClick={e=>{if(e.target===ref.current)onClose();}}><div className="modal-top"><h2>{title}</h2><button className="icon-button" aria-label="关闭" onClick={onClose}><X size={20}/></button></div>{children}</dialog>;
}
function Soul({name}:{name:string|undefined}){return <span className="soul"><i style={{background:soulColors[name??'']}}/>{name??'—'}</span>;}
export default function App(){
 const [page,setPage]=useState<'planner'|'encyclopedia'>('planner'),[encySkill,setEncySkill]=useState<string|null>(null);
 const [state,setState]=useState<State>(initialState),[loaded,setLoaded]=useState(false),[loadError,setLoadError]=useState('');
 const [saveLabel,setSaveLabel]=useState('正在读取'),[notice,setNotice]=useState(''),[history,setHistory]=useState<State[]>([]);
 const [tier,setTier]=useState('');
 const [query,setQuery]=useState(''),[branch,setBranch]=useState('全部分支'),[filter,setFilter]=useState('全部技能'),[soul,setSoul]=useState('全部魂质');
 const [view,setView]=useState<'tree'|'list'>('tree'),[original,setOriginal]=useState(false);
 const [selected,setSelected]=useState<string|null>(null),[target,setTarget]=useState<Slot|null>(null),[settings,setSettings]=useState(false),[help,setHelp]=useState(false);
 const [pendingImport,setPendingImport]=useState<State|null>(null),[confirmCorrection,setConfirmCorrection]=useState(false);
 const inputRef=useRef<HTMLInputElement>(null),searchRef=useRef<HTMLInputElement>(null),stateRef=useRef(state),queue=useRef(Promise.resolve());
 stateRef.current=state;
 useEffect(()=>{loadState().then(s=>{setState(s);setLoaded(true);setSaveLabel('已自动保存至本机');}).catch(()=>{setLoadError('无法读取本机记录。为避免覆盖已有数据，请重试，或导入已有备份。');setSaveLabel('读取失败');});},[]);
 function update(next:State,message=''){
  if(!loaded)return;
  const stamped={...next,updatedAt:new Date().toISOString()};
  setHistory(h=>[...h.slice(-29),stateRef.current]);setState(stamped);persist(stamped);
  if(message)setNotice(message);
 }
 function persist(next:State){setSaveLabel('正在保存…');queue.current=queue.current.catch(()=>{}).then(()=>saveState(next)).then(()=>setSaveLabel('已自动保存至本机')).catch(()=>{setSaveLabel('保存失败，请导出备份');setNotice('本机保存失败，请立即导出备份。当前页面中的修改仍保留。');});}
 function undo(){const prev=history.at(-1);if(!prev)return;setState(prev);setHistory(h=>h.slice(0,-1));persist(prev);setNotice('已撤销上一步操作');}
 function mutate(fn:(next:State)=>void,message=''){const next=structuredClone(stateRef.current);fn(next);update(next,message);}
 useEffect(()=>{if(!notice)return;const id=setTimeout(()=>setNotice(''),6000);return()=>clearTimeout(id);},[notice]);
 useEffect(()=>{function onKey(e:KeyboardEvent){if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();if(page==='encyclopedia')document.getElementById('ency-search')?.focus();else searchRef.current?.focus();}}window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey);},[page]);
 useEffect(()=>{
  const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;
  const controller=new AbortController();
  Promise.resolve(context.registerTool({name:'search_skills',description:'查询技能的计划位置、可选分支和实际进度；不修改记录。',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{const q=(input as {query?:unknown})?.query;if(typeof q!=='string')throw Error('query 必须是文本');return skills.filter(s=>[s.name,s.id].some(n=>n.includes(q))).map(s=>({name:s.name,options:s.options,plan:stateRef.current.plan[s.id],progress:stateRef.current.progress[s.id]}));}},{signal:controller.signal})).catch(()=>{});
  return()=>controller.abort();
 },[]);
 const owned=skills.filter(s=>(state.progress[s.id].level??0)>0).length;
 const committed=skills.filter(s=>state.progress[s.id].actual).length,attuned=skills.filter(s=>state.progress[s.id].attuned).length;
 const changed=skills.filter(s=>!sameSlot(state.plan[s.id],s.original)).length;
 const plan=original?Object.fromEntries(skills.map(s=>[s.id,s.original])):state.plan;
 const visible=skills.filter(s=>{
  const p=state.progress[s.id];return (!tier||tiers[s.id]===tier)&&[s.name,s.id,...s.aliases].some(n=>n.includes(query.trim()))&&(branch==='全部分支'||plan[s.id].branch===branch)&&(soul==='全部魂质'||soulFor(s.id,plan[s.id].branch)===soul)&&(filter==='全部技能'||filter==='已获得'&&(p.level??0)>0||filter==='待上树'&&(p.level??0)>0&&!p.actual||filter==='待调谐'&&!!p.actual&&!p.attuned||filter==='已调谐'&&p.attuned||filter==='计划有调整'&&!sameSlot(state.plan[s.id],s.original));
 });
 const visibleIds=new Set(visible.map(s=>s.id));
 const shownBranches=branch==='全部分支'?branches:[branch];
 const skill=selected?byId[selected]:null,p=selected?state.progress[selected]:null,slot=selected?state.plan[selected]:null;
 const move=selected&&target?previewMove(state,selected,target):null;
 function openSkill(id:string){setSelected(id);setTarget(null);setConfirmCorrection(false);}
 function exportBackup(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`司辰手记-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('备份已导出，包含全部计划和实际进度');}
 async function importBackup(file:File|undefined){if(!file)return;try{if(file.size>2_000_000)throw Error('文件过大，请选择本工具导出的 JSON 备份');setPendingImport(validateState(JSON.parse(await file.text())));}catch(e){setNotice(e instanceof Error?e.message:'备份读取失败');}finally{if(inputRef.current)inputRef.current.value='';}}
 function resetFilters(){setTier('');setQuery('');setBranch('全部分支');setSoul('全部魂质');setFilter('全部技能');}
 return <div className="app-shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark"><GitBranch size={25}/></div><div><strong>司辰手记</strong><span>BOOK OF HOURS</span></div></div>
   <div className="nav-caption">图书管理员的工作台</div>
   <button className={page==='planner'&&!original?'nav-item active':'nav-item'} onClick={()=>{setPage('planner');setOriginal(false);}}><GitBranch size={18}/>智慧之树<ChevronRight size={15}/></button>
   <button className={page==='planner'&&original?'nav-item active':'nav-item'} onClick={()=>{setPage('planner');setOriginal(true);}}><BookOpen size={18}/>原始规划<small>Excel</small></button>
   <button className={page==='encyclopedia'?'nav-item active':'nav-item'} onClick={()=>{setEncySkill(null);setPage('encyclopedia');}}><BookOpen size={18}/>资料百科<ChevronRight size={15}/></button><div className="sidebar-section"><div className="nav-caption">本局进度</div><div className="side-stat"><span>已获得技能</span><b>{owned}<small> / 73</small></b></div><div className="side-stat"><span>已上树</span><b>{committed}<small> / 73</small></b></div><div className="progress-track"><div style={{width:`${committed/73*100}%`}}/></div><div className="side-stat"><span>已调谐</span><b className="red-text">{attuned}</b></div></div>
   <div className="sidebar-tip"><Bookmark size={18}/><p>新技能到手？<br/>搜名称，看看能否<br/>提前安排一个位置。</p><kbd>Ctrl K</kbd></div>
   <div className="sidebar-bottom"><button className="nav-item" onClick={()=>setHelp(true)}><Info size={17}/>使用与数据说明</button><span>仅保存在当前浏览器 · 建议定期备份</span></div>
  </aside>
  <main><header><div className="breadcrumb">司辰之书 <span>/</span> 技能与魂质</div><div className="top-actions"><span className={saveLabel.includes('失败')?'save-label error':'save-label'}><Check size={14}/>{saveLabel}</span><button onClick={undo} disabled={!history.length||!loaded}><Undo2 size={16}/>撤销</button><button onClick={exportBackup} disabled={!loaded}><Download size={16}/>导出备份</button><button onClick={()=>inputRef.current?.click()}><Upload size={16}/>导入</button><input type="file" accept=".json,application/json" hidden ref={inputRef} onChange={e=>void importBackup(e.target.files?.[0])}/></div></header>
  <div hidden={page!=='planner'}><section className="workspace"><div className="page-heading"><div><div className="eyebrow">THE TREE OF WISDOM</div><h1>{original?'原始上树规划':'智慧之树'}</h1><p>{original?'保留 Excel 的最初安排，随时对照当前计划。':'找到技能，调整位置，记下每一次成长。'}</p></div><button className="subtle" onClick={()=>setSettings(true)} disabled={!loaded}><Settings2 size={17}/>记录槽位解锁</button></div>
   {loadError&&<div className="error-banner">{loadError}<button onClick={()=>location.reload()}>重新读取</button></div>}
   <div className="summary-strip"><span><b>73</b> 项技能</span><span><b>{committed}</b> 已上树</span><button onClick={()=>setFilter('待调谐')}><b>{committed-attuned}</b> 待调谐</button><button onClick={()=>setFilter('计划有调整')}><b>{changed}</b> 项计划调整</button><span className="summary-source"><BookOpen size={14}/>来自你的 Excel 规划</span></div>
   <div className="toolbar"><label className="search"><Search size={19}/><input ref={searchRef} value={query} onChange={e=>{setQuery(e.target.value);if(e.target.value)setView('list');}} placeholder="搜索技能名称…" aria-label="搜索技能"/>{query?<button className="icon-button" aria-label="清除搜索" onClick={()=>setQuery('')}><X size={16}/></button>:<kbd>Ctrl K</kbd>}</label><select aria-label="筛选分支" value={branch} onChange={e=>setBranch(e.target.value)}>{['全部分支',...branches].map(x=><option key={x}>{x}</option>)}</select><select aria-label="筛选进度" value={filter} onChange={e=>setFilter(e.target.value)}>{['全部技能','已获得','待上树','待调谐','已调谐','计划有调整'].map(x=><option key={x}>{x}</option>)}</select><select aria-label="筛选推荐评级" value={tier} onChange={e=>setTier(e.target.value)}><option value="">全部评级</option><option>T0</option><option>T1</option></select><div className="view-switch"><button aria-label="树表视图" aria-pressed={view==='tree'} className={view==='tree'?'chosen':''} onClick={()=>setView('tree')}><LayoutGrid size={18}/></button><button aria-label="列表视图" aria-pressed={view==='list'} className={view==='list'?'chosen':''} onClick={()=>setView('list')}><List size={18}/></button></div></div>
   <div className="legend"><span>魂质收益</span>{Object.keys(soulColors).map(n=><button key={n} className={soul===n?'legend-item selected':'legend-item'} onClick={()=>setSoul(soul===n?'全部魂质':n)}><Soul name={n}/></button>)}{(tier||query||branch!=='全部分支'||filter!=='全部技能'||soul!=='全部魂质')&&<button className="text-button" onClick={resetFilters}>清除筛选</button>}</div>
   <div className="board-caption"><span>{original?'原始规划 · 只读对照':'当前计划'} <small> / {visible.length} 项技能</small></span><span><Lock size={13}/>已上树位置锁定 <i/> 红字表示已调谐</span></div>
   {!loaded&&!loadError?<div className="empty">正在读取技能记录…</div>:visible.length===0?<div className="empty"><Search size={30}/><h3>没有找到符合条件的技能</h3><p>试试缩短名称，或清除筛选。</p><button onClick={resetFilters}>显示全部技能</button></div>:view==='tree'?<div className="tree-scroll"><div className="tree-grid" style={{gridTemplateColumns:`36px repeat(${shownBranches.length}, minmax(108px, 1fr))`,minWidth:shownBranches.length>3?`${shownBranches.length*120+36}px`:undefined}}><div className="rank-head">档位</div>{shownBranches.map((b,i)=><div className="branch-head" key={b}><span className="branch-number">{String(branches.indexOf(b)+1).padStart(2,'0')}</span><strong>{b}</strong><small>{skills.filter(s=>state.progress[s.id].actual?.branch===b).length} 已上树</small></div>)}
   {Array.from({length:9},(_,r)=><div className="grid-row" key={r}><div className="rank-number">{r+1}</div>{shownBranches.map(b=>{
    const s=skills.find(x=>sameSlot(plan[x.id],{branch:b,rank:r+1}));const unlocked=state.unlocked.includes(slotKey({branch:b,rank:r+1}));
    if(!s)return <button className={`tree-card vacant ${unlocked?'unlocked':''}`} key={b} onClick={()=>setSettings(true)} aria-label={`${b} ${r+1} 档空位`}><span>空位</span><small>{unlocked?'已记录解锁':'未记录解锁'}</small></button>;
    const pr=state.progress[s.id],color=soulColors[soulFor(s.id,plan[s.id].branch)!];return <button key={b} disabled={!visibleIds.has(s.id)||!loaded} className={`tree-card ${pr.actual?'committed':''} ${pr.attuned?'attuned':''} ${visibleIds.has(s.id)?'':'dimmed'}`} style={{'--soul':color} as CSSProperties} onClick={()=>openSkill(s.id)} aria-label={`${s.name}，${b} ${r+1} 档，${status(pr)}`}><div className="card-top"><span>{soulFor(s.id,plan[s.id].branch)}</span>{pr.actual?<Lock size={12}/>:!sameSlot(state.plan[s.id],s.original)?<ArrowLeftRight size={12}/>:null}</div><strong>{s.name} <TierBadge id={s.id}/></strong><LessonCode id={s.id} compact/><div className="card-bottom"><small>{pr.level===null?'等级未记录':pr.level===0?'未获得':`Lv. ${pr.level}`}</small><span>{pr.attuned?'已调谐':pr.actual?'待调谐':(pr.level??0)>0?'待上树':'·'}</span></div></button>;
   })}</div>)}</div></div>:<div className="table-scroll"><table><thead><tr><th>技能</th><th>当前等级</th><th>{original?'原始位置':'计划位置'}</th><th>魂质</th><th>进度</th><th/></tr></thead><tbody>{visible.map(s=><tr key={s.id}><td><button className={`skill-link ${state.progress[s.id].attuned?'red-text':''}`} onClick={()=>openSkill(s.id)}>{s.name}</button> <TierBadge id={s.id}/><LessonCode id={s.id} compact/></td><td>{state.progress[s.id].level===null?'未记录':state.progress[s.id].level===0?'未获得':`Lv. ${state.progress[s.id].level}`}</td><td>{slotLabel(plan[s.id])}</td><td><Soul name={soulFor(s.id,plan[s.id].branch)}/></td><td>{status(state.progress[s.id])}</td><td><button className="icon-button" aria-label={`查看${s.name}`} onClick={()=>openSkill(s.id)}><ChevronRight size={17}/></button></td></tr>)}</tbody></table></div>}
   <footer><span><Leaf size={14}/>点选技能查看两条分支，并预览提前上树的安排。</span><span>计划 ≠ 实际进度</span></footer>
  </section></div>{page==='encyclopedia'&&<Encyclopedia state={state} initialSkill={encySkill} onSkill={id=>{setPage('planner');openSkill(id);}}/>}</main>
  {notice&&<div className="toast" role="status">{notice}<button aria-label="关闭提示" onClick={()=>setNotice('')}><X size={16}/></button></div>}
  {skill&&p&&slot&&<Modal title={skill.name} onClose={()=>setSelected(null)}><div className="detail-body"><div className="skill-meta"><div className="skill-status"><span className="badge">{status(p)}</span><TierBadge id={skill.id}/></div><div className="skill-actions"><LessonCode key={skill.id} id={skill.id}/><button className="text-button" onClick={()=>{setEncySkill(skill.id);setSelected(null);setPage('encyclopedia');}}>百科资料</button><a href={`https://boh.huijiwiki.com/wiki/${encodeURIComponent(skill.id)}`} target="_blank" rel="noreferrer">查看 Wiki <ExternalLink size={13}/></a></div></div>
   {tiers[skill.id]&&<details className="skill-rating-note"><summary>评级参考说明</summary><TierNote id={skill.id}/></details>}<section className="detail-section"><h3>实际进度</h3><div className="form-row"><label htmlFor="level">当前技能等级</label><select id="level" value={p.level===null?'unknown':p.level} onChange={e=>{const level=e.target.value==='unknown'?null:Number(e.target.value);if(p.actual&&(level===null||level<p.actual.rank)){setNotice('已上树技能的等级不能低于实际上树档位，请先纠正上树记录');return;}mutate(n=>{n.progress[skill.id].level=level;});}}><option value="unknown">未记录</option><option value="0">未获得</option>{Array.from({length:9},(_,i)=><option key={i+1} value={i+1}>{i+1} 级 · 已获得</option>)}</select></div>
    {!p.actual?<><label className="check-row"><input type="checkbox" checked={state.unlocked.includes(slotKey(slot))} onChange={e=>mutate(n=>{n.unlocked=e.target.checked?[...new Set([...n.unlocked,slotKey(slot)])]:n.unlocked.filter(k=>k!==slotKey(slot));})}/>游戏中「{slotLabel(slot)}」已解锁</label><button className="primary full" disabled={commitProblems(state,skill.id).length>0} onClick={()=>update(commitSkill(state,skill.id),'已记录实际上树')}><Check size={16}/>记录已上树 · {slotLabel(slot)}</button>{commitProblems(state,skill.id).length>0&&<p className="hint">{commitProblems(state,skill.id).join('；')}</p>}</>:<><div className="actual-place"><Lock size={16}/>{slotLabel(p.actual)}<Soul name={soulFor(skill.id,p.actual.branch)}/></div><label className="check-row attune-check"><input type="checkbox" checked={p.attuned} onChange={e=>mutate(n=>{n.progress[skill.id].attuned=e.target.checked;},e.target.checked?'已标记调谐完成':'已恢复为待调谐')}/>已调谐 <small>已用此技能完成一次魂质进阶</small></label><button className="text-button" onClick={()=>setConfirmCorrection(!confirmCorrection)}>纠正上树记录</button>{confirmCorrection&&<div className="warning-box">仅用于纠正误录；游戏中的呈递无法撤销。<button onClick={()=>{mutate(n=>{n.progress[skill.id].actual=null;n.progress[skill.id].attuned=false;},'已清除这项技能的上树和调谐记录');setConfirmCorrection(false);}}>确认清除记录</button></div>}</>}
   </section>
   <section className="detail-section"><h3>上树安排 <span>{p.actual?'已固定':'点击档位预览调整'}</span></h3><div className="plan-reference"><span>原始</span>{slotLabel(skill.original)}<br/><span>当前</span><b>{slotLabel(slot)}</b></div>
    {skill.options.map(o=><div className="branch-option" key={o.branch}><div><b>{o.branch}</b><Soul name={o.soul}/></div><div className="rank-picker">{Array.from({length:9},(_,i)=>{const dest={branch:o.branch,rank:i+1};const r=previewMove(state,skill.id,dest),here=sameSlot(dest,slot);return <button key={i} disabled={!!p.actual} className={`${here?'current ':''}${target&&sameSlot(target,dest)?'selected ':''}${!here&&!r.ok?'blocked':''}`} title={here?'当前计划':r.reason} aria-label={`预览${o.branch} ${i+1} 档`} onClick={()=>setTarget(dest)}>{i+1}</button>;})}</div></div>)}
    {target&&move&&<div className={`move-preview ${move.ok?'':'invalid'}`}><h4><ArrowLeftRight size={17}/>{move.reason}</h4>{move.ok&&<><div className="move-line"><b>{skill.name}</b><span>{slotLabel(slot)} <ArrowRight size={12}/> {slotLabel(target)}</span><small>魂质：{soulFor(skill.id,slot.branch)} → {soulFor(skill.id,target.branch)}</small></div>{move.displaced&&<div className="move-line"><b>{byId[move.displaced].name}</b><span>{slotLabel(target)} <ArrowRight size={12}/> {slotLabel(slot)}</span><small>魂质：{soulFor(move.displaced,target.branch)} → {soulFor(move.displaced,slot.branch)}</small></div>}{move.warnings.map(w=><p className="hint" key={w}>{w}</p>)}<button className="primary full" onClick={()=>{update(moveSkill(state,skill.id,target),move.displaced?'已交换两项技能的计划位置':'已移入计划空位');setTarget(null);}}>确认{move.displaced?'交换计划':'调整计划'}</button><p className="hint">仅调整计划，不会标记实际上树。</p></>}</div>}
   </section><label className="note-label">备注<textarea maxLength={2000} value={p.note} onChange={e=>mutate(n=>{n.progress[skill.id].note=e.target.value;})} placeholder="记下培养顺序、暂缓原因…" rows={2}/></label>
  </div></Modal>}
  {settings&&<Modal title="记录槽位解锁" onClose={()=>setSettings(false)} wide><div className="detail-body"><p className="hint">按游戏中的智慧之树勾选可用槽位。这里只记录实际解锁，不推测分支捷径。已占用槽位不能取消。</p><div className="unlock-grid">{branches.map(b=><div key={b}><h3>{b}</h3>{Array.from({length:9},(_,i)=>{const k=slotKey({branch:b,rank:i+1}),taken=skills.some(s=>sameSlot(state.progress[s.id].actual,{branch:b,rank:i+1}));return <label className="check-row" key={k}><input type="checkbox" checked={taken||state.unlocked.includes(k)} disabled={taken} onChange={e=>mutate(n=>{n.unlocked=e.target.checked?[...new Set([...n.unlocked,k])]:n.unlocked.filter(x=>x!==k);})}/>{i+1} 档 {taken?<Lock size={12}/>:null}</label>;})}</div>)}</div><button className="primary" onClick={()=>setSettings(false)}>完成</button></div></Modal>}
  {pendingImport&&<Modal title="导入备份" onClose={()=>setPendingImport(null)}><div className="detail-body"><p>备份包含 {skills.filter(s=>pendingImport.progress[s.id].actual).length} 个已上树技能、{skills.filter(s=>pendingImport.progress[s.id].attuned).length} 个已调谐技能。</p><p className="hint">导入会替换当前计划和进度，可用“撤销”恢复。建议先导出当前备份。</p><div className="modal-actions"><button onClick={exportBackup}>先导出当前备份</button><button className="primary" onClick={()=>{const next=pendingImport;if(!loaded){setState(next);setLoaded(true);setLoadError('');persist(next);}else update(next,'备份已恢复');setPendingImport(null);}}>确认恢复备份</button></div></div></Modal>}
  {help&&<Modal title="使用与数据说明" onClose={()=>setHelp(false)}><div className="detail-body help"><h3>新技能到手后</h3><ol><li>搜索名称，记录当前等级。</li><li>查看两个可选分支，点击更早的档位。</li><li>确认交换预览，再去游戏中上树。</li><li>按游戏画面勾选槽位解锁，记录已上树。</li><li>用技能完成魂质进阶后，勾选“已调谐”。</li></ol><h3>你的原表</h3><p>已导入“上树”页的 73 项技能。末尾数字、粗斜体、第 13–14 行忽略。底色代表魂质收益，红字代表已调谐；当前源文件没有红字进度。</p><p>已上树的技能锁定实际位置；“纠正记录”仅修正误录。未上树技能可互换计划，等级不足不妨碍安排未来位置。</p><h3>保存与备份</h3><p>记录只保存在当前浏览器的本机数据中。请保持相同访问地址，并定期导出 JSON 备份；换浏览器或清理网站数据后需要导入恢复。</p><h3>规则来源</h3><p>可选分支与魂质收益参照 <a href="https://boh.huijiwiki.com/wiki/列表/魂质获得" target="_blank" rel="noreferrer">司辰之书中文 Wiki</a>。槽位解锁由你手动确认，暂不计算工作台与回忆是否足够。</p><p>兼容别名：原表“虬蟠与裂缝”对应 Wiki“虬蟠与裂隙”。</p></div></Modal>}
 </div>;
}
