import LessonCode from './LessonCode';
import {tiers,TierBadge,TierNote} from './tiers';
import {useEffect,useRef,useState} from 'react';
import {BookOpen,Search,X,ExternalLink,ArrowLeft,ArrowRight} from 'lucide-react';
import {entries,categories,aspects,searchEntries,references,type Entry} from './encyclopedia-model';
import {branches,slotLabel,status,type State} from './model';
import './encyclopedia.css';
export default function Encyclopedia({state,onSkill,initialSkill}:{state:State;onSkill:(id:string)=>void;initialSkill:string|null}){
 const [tier,setTier]=useState('');
 const [query,setQuery]=useState(''),[category,setCategory]=useState('全部'),[aspect,setAspect]=useState(''),[branch,setBranch]=useState(''),[spoilers,setSpoilers]=useState(false),[limit,setLimit]=useState(36),[selected,setSelected]=useState<Entry|null>(null),[trail,setTrail]=useState<Entry[]>([]);
 const search=useRef<HTMLInputElement>(null),dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{if(initialSkill)setSelected(entries.find(e=>e.category==='技能'&&e.skillId===initialSkill)??null);},[initialSkill]);
 useEffect(()=>{setLimit(36);},[query,category,aspect,branch,spoilers,tier]);
 useEffect(()=>{if(selected){dialog.current?.showModal();dialog.current?.scrollTo(0,0);}else dialog.current?.close();},[selected]);
 const results=searchEntries(query,category,aspect,branch,spoilers).filter(e=>!tier||(e.category==='技能'&&tiers[e.skillId??'']===tier));
 function open(e:Entry){if(selected)setTrail(t=>[...t,selected]);setSelected(e);}
 function close(){setSelected(null);setTrail([]);}
 function clear(){setTier('');setQuery('');setCategory('全部');setAspect('');setBranch('');}
 return <section className="workspace encyclopedia"><div className="page-heading"><div><div className="eyebrow">THE LIBRARIAN’S COMPENDIUM</div><h1>图书管理员百科</h1><p>查找回忆、制作与进阶线索，随时回到你的技能计划。</p></div><BookOpen size={36} className="book-emblem"/></div>
 <div className="ency-source"><span>{entries.length} 条本地资料 · Excel + Wiki 规则摘要</span><span>资料整理于 2026-09-22 · 非完整 Wiki 镜像</span></div>
 <div className="toolbar"><label className="search"><Search size={19}/><input id="ency-search" ref={search} aria-label="搜索百科" placeholder="搜索名称、材料、获取方式… 多词用空格分隔" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&<button className="icon-button" aria-label="清除百科搜索" onClick={()=>setQuery('')}><X size={16}/></button>}</label><select aria-label="百科准则" value={aspect} onChange={e=>setAspect(e.target.value)}><option value="">全部准则</option>{aspects.map(a=><option key={a}>{a}</option>)}</select><select aria-label="百科分支" value={branch} onChange={e=>setBranch(e.target.value)}><option value="">全部智慧分支</option>{branches.map(b=><option key={b}>{b}</option>)}</select><select aria-label="百科推荐评级" value={tier} onChange={e=>{setTier(e.target.value);if(e.target.value)setCategory('技能');}}><option value="">全部评级</option><option>T0</option><option>T1</option></select></div>
 <div className="ency-categories">{['全部',...categories].map(c=><button key={c} aria-pressed={category===c} className={category===c?'active':''} onClick={()=>setCategory(c)}>{c}<small>{entries.filter(e=>(c==='全部'||e.category===c)&&(spoilers||!e.spoiler)).length}</small></button>)}</div>
 <div className="ency-results"><span>找到 {results.length} 条资料</span><label><input type="checkbox" checked={spoilers} onChange={e=>setSpoilers(e.target.checked)}/>显示闰识剧透</label><button className="text-button" onClick={clear}>重置筛选</button></div>
 <div className="ency-grid">{results.slice(0,limit).map(e=><button className="ency-card" key={e.id} onClick={()=>open(e)}><span className="ency-kind">{e.category}{e.spoiler?' · 剧透':''}</span><h3>{e.name} {e.category==='技能'&&<TierBadge id={e.skillId??''}/>}</h3>{e.category==='技能'&&<LessonCode id={e.skillId??''} compact/>}<div className="aspect-tags">{Object.entries(e.aspects).map(([a,n])=><span key={a}>{a}{n??''}</span>)}</div><p>{e.fields.find(f=>['获取／原表提示','制作需求','使用技能','位置／说明','进阶分支','规则摘要','定位','邀请条件','说明'].includes(f.label))?.value||e.branches.join(' · ')||'查看资料与来源'}</p><div className="ency-card-bottom"><span>{e.category==='技能'&&e.skillId?status(state.progress[e.skillId]):e.branches.join(' / ')||e.sources[0].split('!')[0]}</span><ArrowRight size={15}/></div></button>)}</div>
 {!results.length&&<div className="empty"><Search size={30}/><h3>没有找到资料</h3><p>试试缩短关键词，或取消准则、分支筛选。</p><button onClick={clear}>显示全部</button></div>}
 {results.length>limit&&<button className="ency-more" onClick={()=>setLimit(n=>n+36)}>再显示 36 条（还有 {results.length-limit} 条）</button>}
 <details className="ency-attribution"><summary>资料来源与范围</summary><p>数据来自你的《司辰之书.xlsx》，条目保留工作表与单元格位置。饮食优先使用“饮食”页，“食谱”页差异单独展示。原表缺失值不补猜；准则只有名称而无数字时，代表接受／关联准则。</p><p>工作台筛选仅表示分支或准则关联，不自动保证可进阶。配方准则表示需求，其余物品的数字表示提供的强度。关联资料是名称引用，仍需查看具体条件。</p><p>规则摘要参考 <a href="https://boh.huijiwiki.com/wiki/首页" target="_blank" rel="noreferrer">司辰之书中文 Wiki</a>。原表首页声明采用 <a href="https://creativecommons.org/licenses/by-sa/4.0/deed.zh-hans" target="_blank" rel="noreferrer">CC BY-SA 4.0</a>，并致谢中文 Wiki、碎门之钥及 Fandom Wiki；游戏内容版权属于 Weather Factory。这里对原表资料进行了结构化整理。</p></details>
 <dialog ref={dialog} className="modal wide ency-dialog" onCancel={e=>{e.preventDefault();close();}} onClick={e=>{if(e.target===dialog.current)close();}}>{selected&&<><div className="modal-top"><div>{trail.length>0&&<button className="text-button" onClick={()=>{setSelected(trail.at(-1)!);setTrail(t=>t.slice(0,-1));}}><ArrowLeft size={14}/>返回上一条</button>}<span className="ency-kind">{selected.category}</span><h2>{selected.name}</h2></div><button className="icon-button" aria-label="关闭百科详情" onClick={close}><X size={20}/></button></div><div className="detail-body"><div className="aspect-tags">{Object.entries(selected.aspects).map(([a,n])=><span key={a}>{a}{n??''}</span>)}</div>
 {selected.skillId&&state.progress[selected.skillId]&&<div className="ency-plan"><div><strong>你的技能记录 · {selected.skillId}</strong><p>{slotLabel(state.plan[selected.skillId])} · {status(state.progress[selected.skillId])}</p></div><button className="primary" onClick={()=>{close();onSkill(selected.skillId!);}}>查看／调整上树</button></div>}
 {selected.category==='技能'&&<LessonCode key={selected.id} id={selected.skillId??''}/>} {selected.category==='技能'&&<TierNote id={selected.skillId??''}/>}<dl className="ency-fields">{selected.fields.map((f,i)=><div key={i}><dt>{f.label}</dt><dd>{f.value}</dd></div>)}</dl>
 {selected.sections.map((s,i)=><section className="detail-section" key={i}><h3>{s.title}</h3><div className="table-scroll"><table><thead><tr>{s.columns.map((c,j)=><th key={j}>{c}</th>)}</tr></thead><tbody>{s.rows.map((r,k)=><tr key={k}>{r.map((v,j)=><td key={j}>{v||'—'}</td>)}</tr>)}</tbody></table></div></section>)}
 {references(selected,spoilers).length>0&&<section className="detail-section"><h3>关联资料 <span>同名、技能关联或原文提及</span></h3><div className="ency-links">{references(selected,spoilers).map(e=><button key={e.id} onClick={()=>open(e)}><span>{e.category}</span>{e.name}<ArrowRight size={14}/></button>)}</div></section>}
 <div className="ency-citations"><strong>资料来源</strong>{selected.sources.map(s=><span key={s}>{s.startsWith('Wiki!')?s.replace('Wiki!','Wiki · '):`司辰之书.xlsx · ${s}`}</span>)}<a target="_blank" rel="noreferrer" href={selected.wiki||`https://boh.huijiwiki.com/wiki/Special:Search?search=${encodeURIComponent(selected.skillId||selected.name)}`}>{selected.wiki?'阅读 Wiki 规则原文':'在 Wiki 检索此条目'}<ExternalLink size={13}/></a></div></div></>}</dialog>
 </section>;
}
